#!/bin/bash
#javac CTCOffice/*.java \
#      TNM/*.java \
#      TKM/*.java \
#      TKC/test/*.java \
#      TKC/util/*.java \
#      MBO/*.java \
#      SSC/*.java
javac -cp .:controlP5.jar:core.jar TNM/*.java TKM/*.java CTCOffice/*.java TKC/util/*.java
